version: 2.1

jobs:
  build-docker-image:
    docker:
      - image: docker
    steps:
      - setup_remote_docker
      - checkout
      - run: sh build.sh

  quality-checks:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm ci
      - run: npm run prettier:check
      - run: npm test

workflows:
  version: 2.0

  build:
    jobs:
      - build-docker-image
      - quality-checks
