version: 2.1

jobs:
  quality-checks:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm ci
      - run: npm run prettier:check
      - run: npm test

  build-docker-image:
    docker:
      - image: docker
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Build docker image
          command: |
            sh build.sh
      - when:
          condition:
            equal: [master, << pipeline.git.branch >>]
          steps:
            - run:
                name: Login to Docker Hub
                command: |
                  echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            - run:
                name: Publish docker image on Docker Hub
                command: |
                  docker image push zenika/sensei:latest

workflows:
  version: 2.0

  build:
    jobs:
      - quality-checks
      - build-docker-image:
          context: docker-hub-zenika
